### ISSUE TITLE
Add option to rewind video

### ISSUE THREAD

**Issue by cocofoco** [juliang22/ObsidianTimestampNotes#7]
Would it be possible to add a shortcut to rewind the video by 5 seconds?

I sometimes get distracted while taking notes on a lecture and end up missing a phrase, and it would be helpful to have a shortcut to rewind the video by 5 seconds.

Similarly, would it be possible to skip forward 5 seconds?

**Comment by huyz** [comment]
I wonder if there's an easy way to have access to _all_ the keyboard shortcuts that the players already support (e.g., YouTube lets you hit `j`, `k`, and `l` to rewind, pause, and skip forward).  So instead of reimplementing all the shortcuts for all the different video players, it might be simpler to figure out a way to forward any arbitrary key combination to the player without leaving the current note.

For example, perhaps there could be a way to hit a leader key combination (such as `^K` in VSCode or `^W` in vim), which would make the plugin wait for the next key combination.  The plugin would then redirect that next key combination to the video player without the note losing focus and cursor position.

**Comment by rrherr** [comment]
Came here to say this — I'd love to a keyboard shortcut to rewind 5 seconds!
