### ISSUE TITLE
[bug] The layout doesn't work well for a horizontal pane

### ISSUE THREAD

**Issue by huyz** [juliang22/ObsidianTimestampNotes#8]
It seems the layout was designed to have the video in a tall vertical pane on the side.  The video is stretched horizontally within the note.  In my Obsidian, that's wasteful as most of the bottom of that pane is just whitespace.

Videos tend to be more wide than tall. So it makes sense to me to try to move the video pane to the bottom of my app and make it horizontal instead.  Especially since I have a 2-pane side-by-side layout usually, I can basically try to dedicate the bottom-left quadrant of my screen to the Timestamp Video pane; then that would minimize the amount of wasteful white space.

Unfortunately, for some reason the video is squished from the bottom and ends up looking like this:

![screenshot 2022-07-10T135502Z](https://user-images.githubusercontent.com/128394/178147876-27a5c9c8-9031-48e2-9a71-c0d67e723786.png)

Can't really see much.

**Comment by enly1** [comment]
The issue here is it seems to be setting the video frame height to a small portion of the pane height.  If you make the pane taller, it scales the video a bit, but should just use the available space more efficiently.  Then it would be great.
I did find undocking it and putting it in the main edit space provided an option for me to get a viewable size video; however, 1/4 of the screen then is wasted.

Suspect some minor tweaks would fix this up nicely.

ps - Was viewing a youtube video also.
